name: "Test: CI"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  audit:
    name: "Audit Dependencies"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: useblacksmith/setup-node@v5
        with:
          node-version-file: .nvmrc
      - run: pnpm audit --audit-level=moderate

  static-analysis:
    name: "Static Analysis"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: useblacksmith/setup-node@v5
        with:
          node-version-file: .nvmrc
      - run: pnpm install --frozen-lockfile

      - name: Run Biome CI
        run: pnpm lint:ci

      - name: Run TypeScript Typecheck
        run: pnpm typecheck

  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: useblacksmith/setup-node@v5
        with:
          node-version-file: .nvmrc
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
